version: '3.8'

services:
  db:
    image: postgres:17.0-alpine
    container_name: don-postgres
    environment:
      POSTGRES_USER: don
      POSTGRES_PASSWORD: don
      POSTGRES_DB: don_v1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
