/*
Developer Overheid API

API for retrieveing all the API's and repositories on Developer Overheid

API version: dev
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the APIListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &APIListItem{}

// APIListItem struct for APIListItem
type APIListItem struct {
	Id *string `json:"id,omitempty"`
	ServiceName *string `json:"service_name,omitempty"`
	Description *string `json:"description,omitempty"`
	Organization *APIListItemOrganization `json:"organization,omitempty"`
	ApiType *string `json:"api_type,omitempty"`
	ApiAuthentication *string `json:"api_authentication,omitempty"`
	Environments []APIListItemEnvironmentsInner `json:"environments,omitempty"`
	Contact *APIListItemContact `json:"contact,omitempty"`
	IsReferenceImplementation *bool `json:"is_reference_implementation,omitempty"`
	TermsOfUse *APIListItemTermsOfUse `json:"terms_of_use,omitempty"`
}

// NewAPIListItem instantiates a new APIListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAPIListItem() *APIListItem {
	this := APIListItem{}
	return &this
}

// NewAPIListItemWithDefaults instantiates a new APIListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAPIListItemWithDefaults() *APIListItem {
	this := APIListItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *APIListItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *APIListItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *APIListItem) SetId(v string) {
	o.Id = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *APIListItem) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *APIListItem) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *APIListItem) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *APIListItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *APIListItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *APIListItem) SetDescription(v string) {
	o.Description = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *APIListItem) GetOrganization() APIListItemOrganization {
	if o == nil || IsNil(o.Organization) {
		var ret APIListItemOrganization
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetOrganizationOk() (*APIListItemOrganization, bool) {
	if o == nil || IsNil(o.Organization) {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *APIListItem) HasOrganization() bool {
	if o != nil && !IsNil(o.Organization) {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given APIListItemOrganization and assigns it to the Organization field.
func (o *APIListItem) SetOrganization(v APIListItemOrganization) {
	o.Organization = &v
}

// GetApiType returns the ApiType field value if set, zero value otherwise.
func (o *APIListItem) GetApiType() string {
	if o == nil || IsNil(o.ApiType) {
		var ret string
		return ret
	}
	return *o.ApiType
}

// GetApiTypeOk returns a tuple with the ApiType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetApiTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ApiType) {
		return nil, false
	}
	return o.ApiType, true
}

// HasApiType returns a boolean if a field has been set.
func (o *APIListItem) HasApiType() bool {
	if o != nil && !IsNil(o.ApiType) {
		return true
	}

	return false
}

// SetApiType gets a reference to the given string and assigns it to the ApiType field.
func (o *APIListItem) SetApiType(v string) {
	o.ApiType = &v
}

// GetApiAuthentication returns the ApiAuthentication field value if set, zero value otherwise.
func (o *APIListItem) GetApiAuthentication() string {
	if o == nil || IsNil(o.ApiAuthentication) {
		var ret string
		return ret
	}
	return *o.ApiAuthentication
}

// GetApiAuthenticationOk returns a tuple with the ApiAuthentication field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetApiAuthenticationOk() (*string, bool) {
	if o == nil || IsNil(o.ApiAuthentication) {
		return nil, false
	}
	return o.ApiAuthentication, true
}

// HasApiAuthentication returns a boolean if a field has been set.
func (o *APIListItem) HasApiAuthentication() bool {
	if o != nil && !IsNil(o.ApiAuthentication) {
		return true
	}

	return false
}

// SetApiAuthentication gets a reference to the given string and assigns it to the ApiAuthentication field.
func (o *APIListItem) SetApiAuthentication(v string) {
	o.ApiAuthentication = &v
}

// GetEnvironments returns the Environments field value if set, zero value otherwise.
func (o *APIListItem) GetEnvironments() []APIListItemEnvironmentsInner {
	if o == nil || IsNil(o.Environments) {
		var ret []APIListItemEnvironmentsInner
		return ret
	}
	return o.Environments
}

// GetEnvironmentsOk returns a tuple with the Environments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetEnvironmentsOk() ([]APIListItemEnvironmentsInner, bool) {
	if o == nil || IsNil(o.Environments) {
		return nil, false
	}
	return o.Environments, true
}

// HasEnvironments returns a boolean if a field has been set.
func (o *APIListItem) HasEnvironments() bool {
	if o != nil && !IsNil(o.Environments) {
		return true
	}

	return false
}

// SetEnvironments gets a reference to the given []APIListItemEnvironmentsInner and assigns it to the Environments field.
func (o *APIListItem) SetEnvironments(v []APIListItemEnvironmentsInner) {
	o.Environments = v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *APIListItem) GetContact() APIListItemContact {
	if o == nil || IsNil(o.Contact) {
		var ret APIListItemContact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetContactOk() (*APIListItemContact, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *APIListItem) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given APIListItemContact and assigns it to the Contact field.
func (o *APIListItem) SetContact(v APIListItemContact) {
	o.Contact = &v
}

// GetIsReferenceImplementation returns the IsReferenceImplementation field value if set, zero value otherwise.
func (o *APIListItem) GetIsReferenceImplementation() bool {
	if o == nil || IsNil(o.IsReferenceImplementation) {
		var ret bool
		return ret
	}
	return *o.IsReferenceImplementation
}

// GetIsReferenceImplementationOk returns a tuple with the IsReferenceImplementation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetIsReferenceImplementationOk() (*bool, bool) {
	if o == nil || IsNil(o.IsReferenceImplementation) {
		return nil, false
	}
	return o.IsReferenceImplementation, true
}

// HasIsReferenceImplementation returns a boolean if a field has been set.
func (o *APIListItem) HasIsReferenceImplementation() bool {
	if o != nil && !IsNil(o.IsReferenceImplementation) {
		return true
	}

	return false
}

// SetIsReferenceImplementation gets a reference to the given bool and assigns it to the IsReferenceImplementation field.
func (o *APIListItem) SetIsReferenceImplementation(v bool) {
	o.IsReferenceImplementation = &v
}

// GetTermsOfUse returns the TermsOfUse field value if set, zero value otherwise.
func (o *APIListItem) GetTermsOfUse() APIListItemTermsOfUse {
	if o == nil || IsNil(o.TermsOfUse) {
		var ret APIListItemTermsOfUse
		return ret
	}
	return *o.TermsOfUse
}

// GetTermsOfUseOk returns a tuple with the TermsOfUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *APIListItem) GetTermsOfUseOk() (*APIListItemTermsOfUse, bool) {
	if o == nil || IsNil(o.TermsOfUse) {
		return nil, false
	}
	return o.TermsOfUse, true
}

// HasTermsOfUse returns a boolean if a field has been set.
func (o *APIListItem) HasTermsOfUse() bool {
	if o != nil && !IsNil(o.TermsOfUse) {
		return true
	}

	return false
}

// SetTermsOfUse gets a reference to the given APIListItemTermsOfUse and assigns it to the TermsOfUse field.
func (o *APIListItem) SetTermsOfUse(v APIListItemTermsOfUse) {
	o.TermsOfUse = &v
}

func (o APIListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o APIListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ServiceName) {
		toSerialize["service_name"] = o.ServiceName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Organization) {
		toSerialize["organization"] = o.Organization
	}
	if !IsNil(o.ApiType) {
		toSerialize["api_type"] = o.ApiType
	}
	if !IsNil(o.ApiAuthentication) {
		toSerialize["api_authentication"] = o.ApiAuthentication
	}
	if !IsNil(o.Environments) {
		toSerialize["environments"] = o.Environments
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	if !IsNil(o.IsReferenceImplementation) {
		toSerialize["is_reference_implementation"] = o.IsReferenceImplementation
	}
	if !IsNil(o.TermsOfUse) {
		toSerialize["terms_of_use"] = o.TermsOfUse
	}
	return toSerialize, nil
}

type NullableAPIListItem struct {
	value *APIListItem
	isSet bool
}

func (v NullableAPIListItem) Get() *APIListItem {
	return v.value
}

func (v *NullableAPIListItem) Set(val *APIListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableAPIListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableAPIListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAPIListItem(val *APIListItem) *NullableAPIListItem {
	return &NullableAPIListItem{value: val, isSet: true}
}

func (v NullableAPIListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAPIListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


