// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API register API v1
 *
 * API van het API register (apis.developer.overheid.nl)
 *
 * API version: 1.0.0
 * Contact: developer.overheid@geonovum.nl
 */

package openapi

import (
	"context"
	"net/http"
)



// APIsAPIRouter defines the required methods for binding the api requests to a responses for the APIsAPI
// The APIsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a APIsAPIServicer to perform the required actions, then write the service results to the http response.
type APIsAPIRouter interface { 
	ListApis(http.ResponseWriter, *http.Request)
	RetrieveApi(http.ResponseWriter, *http.Request)
}


// APIsAPIServicer defines the api actions for the APIsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type APIsAPIServicer interface { 
	ListApis(context.Context) (ImplResponse, error)
	RetrieveApi(context.Context, string) (ImplResponse, error)
}
