// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API register API v1
 *
 * API van het API register (apis.developer.overheid.nl)
 *
 * API version: 1.0.0
 * Contact: developer.overheid@geonovum.nl
 */

package openapi




type ApiEnvironmentsInner struct {

	Name string `json:"name,omitempty"`

	ApiUrl string `json:"api_url,omitempty"`

	SpecificationUrl string `json:"specification_url,omitempty"`

	DocumentationUrl string `json:"documentation_url,omitempty"`
}

// AssertApiEnvironmentsInnerRequired checks if the required fields are not zero-ed
func AssertApiEnvironmentsInnerRequired(obj ApiEnvironmentsInner) error {
	return nil
}

// AssertApiEnvironmentsInnerConstraints checks if the values respects the defined constraints
func AssertApiEnvironmentsInnerConstraints(obj ApiEnvironmentsInner) error {
	return nil
}
