// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API register API v1
 *
 * API van het API register (apis.developer.overheid.nl)
 *
 * API version: 1.0.0
 * Contact: developer.overheid@geonovum.nl
 */

package openapi




type ApiOrganisation struct {

	Label string `json:"label,omitempty"`

	Uri string `json:"uri,omitempty"`
}

// AssertApiOrganisationRequired checks if the required fields are not zero-ed
func AssertApiOrganisationRequired(obj ApiOrganisation) error {
	return nil
}

// AssertApiOrganisationConstraints checks if the values respects the defined constraints
func AssertApiOrganisationConstraints(obj ApiOrganisation) error {
	return nil
}
