/*
Developer Overheid API

Testing RepositoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package don_api_register

import (
	"context"
	"testing"

	don_api_register "github.com/developer-overheid-nl/don-api-register"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_don_api_register_RepositoryAPIService(t *testing.T) {

	configuration := don_api_register.NewConfiguration()
	apiClient := don_api_register.NewAPIClient(configuration)

	t.Run("Test RepositoryAPIService ListRepository", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RepositoryAPI.ListRepository(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
